Fix bad substitution

diff --git a/.github/workflows/cache_cleanup.yml b/.github/workflows/cache_cleanup.yml
--- a/.github/workflows/cache_cleanup.yml
+++ b/.github/workflows/cache_cleanup.yml
@@ -18,8 +18,8 @@ jobs:
           echo "Deleting caches..."
           for cacheKey in $cacheKeysForPR
           do
-              echo "Deleting cache: ${$cacheKey}"
-              gh cache delete "${cacheKey}" || echo "Error deleting: ${$cacheKey}"
+              echo "Deleting cache: ${cacheKey}"
+              gh cache delete "${cacheKey}" || echo "Error deleting: ${cacheKey}"
           done
           echo "Done"
         env:
