Debug cache deletion. (#15)

diff --git a/.github/workflows/cache_cleanup.yml b/.github/workflows/cache_cleanup.yml
--- a/.github/workflows/cache_cleanup.yml
+++ b/.github/workflows/cache_cleanup.yml
@@ -10,15 +10,16 @@ jobs:
     steps:
       - name: Cleanup
         run: |
-          echo "Fetching list of cache key"
-          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
+          set -euo pipefail
 
-          ## Setting this to not fail the workflow while deleting cache keys.
-          set +e
+          echo "Fetching list of cache keys for branch '${BRANCH}'."
+          cacheKeysForPR=$(gh cache list --ref "${BRANCH}"" --limit 100 --json id --jq '.[].id')
+
           echo "Deleting caches..."
           for cacheKey in $cacheKeysForPR
           do
-              gh cache delete $cacheKey
+              echo "Deleting cache: ${$cacheKey}"
+              gh cache delete "${cacheKey}" || echo "Error deleting: ${$cacheKey}"
           done
           echo "Done"
         env:
