Correct cache iteration for cache cleanup. (#20)

diff --git a/.github/workflows/cache_cleanup.yml b/.github/workflows/cache_cleanup.yml
--- a/.github/workflows/cache_cleanup.yml
+++ b/.github/workflows/cache_cleanup.yml
@@ -12,11 +12,12 @@ jobs:
         run: |
           set -euo pipefail
 
+          # We could fetch the prefix list and per prefix keep one. But main cannot see the feature branch cahce :-(
           echo "Fetching list of cache keys for head ref '${HEAD_REF}' on PR '${PULL_REQUEST}'."
           cacheKeysForPR=$(gh cache list --ref "${HEAD_REF}" --limit 100 --json id --jq '.[].id')
 
           echo "Deleting caches..."
-          for cacheKey in "${cacheKeysForPR[@]}"; do
+          for cacheKey in ${cacheKeysForPR}"; do
             echo "Deleting cache: ${cacheKey}"
             gh cache delete "${cacheKey}" || echo "Error deleting: ${cacheKey}"
           done
@@ -34,12 +35,12 @@ jobs:
           closedBeforeDate="$(date -Iminutes --date=-4hours)"
           echo "Fetching list of branch names for PRs closed before: ${closedBeforeDate}."
           closedPRs=$(gh pr list -s closed --json headRefName,closedAt --jq "map(select(.closedAt < \"${closedBeforeDate}\"))|.[].headRefName")
-          for closedPR in "${closedPRs[@]}"; do
-            echo "Deleting caches for ${closedPR}..."
+          for closedPR in ${closedPRs}; do
+            echo "Deleting caches for '${closedPR}'..."
             cacheKeysForPR=$(gh cache list --ref "ref/heads/${closedPR}" --limit 250 --json id --jq '.[].id')
-            for cacheKey in "${cacheKeysForPR[@]}"; do
-              echo "Deleting cache: ${cacheKey}"
-              gh cache delete "${cacheKey}" || echo "Error deleting: ${cacheKey}"
+            for cacheKey in ${cacheKeysForPR}; do
+              echo "Deleting cache: '${cacheKey}'"
+              gh cache delete "${cacheKey}" || echo "Error deleting: '${cacheKey}'."
             done
           done
         env:
