Must inherit the secrets

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -145,15 +145,13 @@ jobs:
         run: |
           set -euo pipefail
 
-          env
-
           echo "Fetching list of old caches for key prefix ${{env.CACHE_KEY_PREFIX}}-${{github.ref}}..."
           oldCacheKeys=$(gh cache list  --limit 100 --json id,key,ref,createdAt --jq "map(select(.key|startswith(\"${CACHE_KEY_PREFIX}-${{github.ref}}\")))|sort_by(.createdAt)|.[:-1]|.[].id")
 
           echo "Deleting caches for ${closedPR}..."
           for cacheKey in "${oldCacheKeys[@]}"; do
-            echo "Deleting cache: ${$cacheKey}"
-            gh cache delete "${cacheKey}" || echo "Error deleting: ${$cacheKey}"
+            echo "Deleting cache: ${$acheKey}"
+            gh cache delete "${cacheKey}" || echo "Error deleting: ${cacheKey}"
           done
         env:
           GH_TOKEN: ${{secrets.CACHE_ACCESS}}
